---
title: "Relocation choice for different homophily preferences: hybrid scenarios for Schelling Model"
bibliography: "references.bib"
output:
  pdf_document:
    keep_tex: yes
---


```{r setup, include=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.lp="fig:", warning=FALSE, message=FALSE)
options(digits = 3)
#tinytex::reinstall_tinytex()
# setwd("C:/Users/rocpa/OneDrive/Desktop/AF2/analysis")

library(dplyr)
library(ggplot2)
library(plotly)
library(reshape)
library(reshape2)
library(tidyr)
library(forcats)
#library(xlsx)
library(xtable)
library(gridExtra)
library(kableExtra)
library(RColorBrewer)
library(ggpubr)

# Dataset formation
# basic1 <- read.csv("BACK/DATA/03_03_2022/basic.csv",sep =",",skip = 6)
# basic2 <- read.csv("BACK/DATA/03_03_2022/basic_2.csv",sep =",",skip = 6)
# basic_all <- rbind(basic1,basic2)
# basic_all$ID <- "basic"
# 
# ethnicsize <- read.csv("BACK/DATA/03_03_2022/ethnicsize_10.csv",sep =",",skip = 6)
# ethnicsize2 <- read.csv("BACK/DATA/03_03_2022/ethnicsize_10_2.csv",sep =",",skip = 6)
# ethnicsize$relative_size <- "ethnic"
# ethnicsize_all <- rbind(ethnicsize,ethnicsize2)
# ethnicsize_all$ID <- "ethnicsize"
# 
# 
# valuesize <- read.csv("BACK/DATA/03_03_2022/valuesize_10.csv",sep =",",skip = 6)
# valuesize2 <- read.csv("BACK/DATA/03_03_2022/valuesize_10_2.csv",sep =",",skip = 6)
# valuesize$relative_size <- "value"
# valuesize_all <- rbind(valuesize,valuesize2)
# valuesize_all$ID <- "valuesize"
# 
# sens_con <- read.csv("BACK/DATA/03_03_2022/sens_con.csv",sep =",",skip = 6)
# sens_con2 <- read.csv("BACK/DATA/03_03_2022/sens_con_2.csv",sep =",",skip = 6)
# sens_con_all <- rbind(sens_con,sens_con2)
# sens_con_all$ID <- "sens_con"
# 
# sens_lib <- read.csv("BACK/DATA/03_03_2022/sens_lib.csv",sep =",",skip = 6)
# sens_lib2 <- read.csv("BACK/DATA/03_03_2022/sens_lib_2.csv",sep =",",skip = 6)
# sens_lib_all <- rbind(sens_lib,sens_lib2)
# sens_lib_all$ID <- "sens_lib"
# 
# 
# df <- rbind(basic_all,ethnicsize_all,valuesize_all,sens_con_all,sens_lib_all)
# 
# names(df)[names(df) == "X.run.number."] <- "run"
# names(df)[names(df) == "per_majority"] <- "majority"
# names(df)[names(df) == "X.liberal_maj"] <- "liberal_maj"
# names(df)[names(df) == "X.liberal_min"] <- "liberal_min"
# names(df)[names(df) == "X.step."] <- "step"
# names(df)[names(df) == "X.majority"] <- "majority"
# df$liberal_min <- 50 # no manipulated, % liberals ethnic depends on liberal maj
# write.csv(df,file = "dataset.csv", row.names = FALSE)

# df_basic_libeth and df_basic_conval added later to df
# df <- read.csv("dataset.csv") 
# df_basic_libeth1 <- read.csv("BACK/DATA/03_03_2022/basic_libeth_1.csv",sep =",",skip = 6)
# df_basic_libeth2 <- read.csv("BACK/DATA/03_03_2022/basic_libeth_2.csv",sep =",",skip = 6)
# df_basic_libeth <- rbind(df_basic_libeth1,df_basic_libeth2)
# names(df_basic_libeth)[names(df_basic_libeth) == "X.run.number."] <- "run"
# names(df_basic_libeth)[names(df_basic_libeth) == "X.liberal_maj"] <- "liberal_maj"
# names(df_basic_libeth)[names(df_basic_libeth) == "X.liberal_min"] <- "liberal_min"
# names(df_basic_libeth)[names(df_basic_libeth) == "X.step."] <- "step"
# names(df_basic_libeth)[names(df_basic_libeth) == "X.majority"] <- "majority"
# df_basic_libeth$ID <- "bsc_libeth"
# df_basic_libeth <- relocate(df_basic_libeth,ID,.before = run)
# 
# df_basic_conval1 <- read.csv("BACK/DATA/03_03_2022/basic_conval_1.csv",sep =",",skip = 6)
# df_basic_conval2 <- read.csv("BACK/DATA/03_03_2022/basic_conval_2.csv",sep =",",skip = 6)
# df_basic_conval <- rbind(df_basic_conval1,df_basic_conval2)
# names(df_basic_conval)[names(df_basic_conval) == "X.run.number."] <- "run"
# names(df_basic_conval)[names(df_basic_conval) == "X.liberal_maj"] <- "liberal_maj"
# names(df_basic_conval)[names(df_basic_conval) == "X.liberal_min"] <- "liberal_min"
# names(df_basic_conval)[names(df_basic_conval) == "X.step."] <- "step"
# names(df_basic_conval)[names(df_basic_conval) == "X.majority"] <- "majority"
# df_basic_conval$ID <- "bsc_conval"
# df_basic_conval <- relocate(df_basic_conval,ID,.before = run)
# 
# df <- rbind(df,df_basic_libeth,df_basic_conval)
# df <- relocate(df,ID,.before=run)
# write.csv(df,file="dataset.csv",row.names = F)

df <- read.csv("dataset.csv") %>% select(-c(run,density,step,visualize)) %>%
  group_by(ID,relative_size,dominant_distribution,secondary_distribution,
    majority,liberal_maj,liberal_min,dominant, secondary,con_eth,lib_val,con_val,lib_eth,eth_con_maj,
    eth_con_min, val_con_maj,val_con_min,val_lib_maj,val_lib_min,eth_lib_maj,eth_lib_min) %>% 
  summarise_all(c("m"= mean,"sd"= sd)) 

# dataset baseline (ethnic symmetric) condition (long format for pictures)

df_bsl_pic <- df %>% gather(key = group_bsl, value = Segra_bsl, et_cl_m,et_sq_m,vl_cl_m,vl_sq_m,den_sq_m,den_cl_m)  %>%
  mutate(`outcome_bsl` = fct_relevel(fct_collapse(group_bsl,
                                              "Ethnic" = c("et_sq_m","et_cl_m"),
                                              "Density" = c("den_sq_m","den_cl_m"),
                                              "Value" = c("vl_sq_m","vl_cl_m")),"Ethnic"),
         `orientation_bsl` = fct_relevel(fct_collapse(group_bsl,
                                                  "Conservative" = c("et_sq_m","vl_sq_m","den_sq_m"),
                                                  "Liberal" = c("et_cl_m","vl_cl_m","den_cl_m")), "Conservative"),
         
         )


df_asm_pic <- df %>% gather(key = group_asm, value = Segra_asm, cls_et_sq_bl_m,cls_et_cl_bl_m,cls_et_sq_or_m,cls_et_cl_or_m,
                               cls_vl_sq_bl_m,cls_vl_cl_bl_m,cls_vl_sq_or_m,cls_vl_cl_or_m)%>%
  mutate(`outcome` = fct_relevel(fct_collapse(group_asm,
                                              "Ethnic" = c("cls_et_sq_bl_m","cls_et_cl_bl_m","cls_et_sq_or_m","cls_et_cl_or_m"),
                                              "Value" = c( "cls_vl_sq_bl_m","cls_vl_cl_bl_m","cls_vl_sq_or_m","cls_vl_cl_or_m")), "Ethnic"),
         `type` = fct_relevel(fct_collapse(group_asm,
                                           "Conservative Native" = c("cls_et_sq_bl_m","cls_vl_sq_bl_m"),
                                           "Liberal Native" = c("cls_et_cl_bl_m","cls_vl_cl_bl_m"),
                                           "Conservative Migrant" = c("cls_et_sq_or_m","cls_vl_sq_or_m"),
                                           "Liberal Migrant" = c("cls_et_cl_or_m","cls_vl_cl_or_m")),"Conservative Native" ))


df_asm_bsl <- df %>% gather(key = group_asm, value = Segra_asm, et_sq_bl_m,et_cl_bl_m,et_sq_or_m,et_cl_or_m,
                              vl_sq_bl_m,vl_cl_bl_m,vl_sq_or_m,vl_cl_or_m,
                            den_cl_bl_m,den_sq_bl_m,den_cl_or_m,den_sq_or_m)%>%
  mutate(`outcome` = fct_relevel(fct_collapse(group_asm,
                                              "Ethnic" = c("et_sq_bl_m","et_cl_bl_m","et_sq_or_m","et_cl_or_m"),
                                              "Value" = c( "vl_sq_bl_m","vl_cl_bl_m","vl_sq_or_m","vl_cl_or_m"),
                                              "Density" = c(
"den_sq_or_m","den_cl_or_m","den_sq_bl_m","den_cl_bl_m")), "Ethnic"),
         `type` = fct_relevel(fct_collapse(group_asm,
                         "Conservative Native" = c("et_sq_bl_m","vl_sq_bl_m","den_sq_bl_m"),
                         "Liberal Native" = c("et_cl_bl_m","vl_cl_bl_m","den_cl_bl_m"),
                         "Conservative Migrant" = c("et_sq_or_m","vl_sq_or_m","den_sq_or_m"),
                         "Liberal Migrant" = c("et_cl_or_m","vl_cl_or_m","den_cl_or_m")),
                              "Conservative Native" ))

```

```{r baseline,include = TRUE,  warning = FALSE}

dfpic <- df_bsl_pic %>% filter(ID == "basic" ) %>% filter(con_val == 1 & lib_eth == 1 | con_val == 0 & lib_eth == 0)
dfpic$baseline <- ifelse(dfpic$con_val == 0 & dfpic$lib_eth == 0,"w[sec]==0", "w[sec]==1") %>% factor(levels = c("w[sec]==1","w[sec]==0"))


ggplot(dfpic,aes(x = dominant, y = Segra_bsl, color = outcome_bsl, shape = orientation_bsl)) +
  geom_point(size = 1.5) + geom_line() +
  facet_wrap(~ baseline, dir = "v", labeller = label_parsed) + # labeller(baseline = baseline.labs))+
  scale_color_manual(values = c("Ethnic"="purple","Value"="dark green","Density" = "gray"), labels = c("Ethnic" = "Ethnic exposure","Value"="Value exposure","Density"="Density"),
                     guide = guide_legend(title = "Outcome", order = 1)) +
  scale_shape_manual(values = c("Conservative" = "square", "Liberal" = "circle"), guide = guide_legend(title = "Orientation")) +
  scale_x_continuous(breaks= seq(0,20,by=1), limits=c(0,20)) +
  ylab("Outcome") + xlab("ß dominant") +
  theme_bw() 
ggsave("img_analysis/baseline.jpg",width = 6,height = 5)
```

```{r totsens, ,include = TRUE,  warning = FALSE}

libval.labs <- c("ß value liberal = 0", "ß value liberal = 20")
names(libval.labs) <- c("0", "20")

libv <- df_bsl_pic %>% filter(ID=="sens_lib" & orientation_bsl == "Conservative") %>%
  ggplot(aes(x=con_eth,y=Segra_bsl,color=outcome_bsl)) +
  geom_point(size=1.5, shape = "square") + geom_line() +
  scale_color_manual(name = "Outcome",
                     values = c("Ethnic" = "purple","Value" = "darkgreen", "Density" = "gray"),
                     labels = c("Ethnic" = "Ethnic\nexposure", "Value" = "Value\nexposure","Density" = "Density")) +
  facet_wrap(~ as.factor(lib_val), labeller = as_labeller(c("0" = "ß value liberal = 0","20" = "ß value liberal = 20"))) +
  ylab("Outcome conservative") +
  xlab("ß ethnic conservative") +
 # ggtitle("Effect liberal value preferences over conservative agents") +
  theme_bw()

cone <- df_bsl_pic %>% filter(ID=="sens_con" & orientation_bsl == "Liberal") %>%
  ggplot(aes(x=lib_val,y=Segra_bsl,color=outcome_bsl)) +
  geom_point(size=1.5, shape = "circle") + geom_line() +
  scale_color_manual(name = "Outcome",
                     values = c("Ethnic" = "purple","Value" = "darkgreen", "Density" = "gray"),
                     labels = c("Ethnic" = "Ethnic\nexposure", "Value" = "Value\nexposure","Density" = "Density")) +
  facet_wrap(~as.factor(con_eth), labeller = as_labeller(c("0" = "ß ethnic conservative = 0","20" = "ß ethnic conservative = 20"))) +
  ylab("Outcome liberal") +
  xlab("ß value liberal") +
 # ggtitle("Effect conservative ethnic preferences over liberal agents") +
  theme_bw()

ggpubr::ggarrange(libv,cone,nrow = 2, common.legend = TRUE, legend = "right")
ggsave("img_analysis/totsens.jpg",width = 7,height = 5)

```

```{r libeth,include = TRUE}
 
 outcome.labs <- c("Ethnic exposure", "Density", "Value exposure")
names(outcome.labs) <- c("Ethnic", "Density", "Value")


ggplot(df_bsl_pic[df_bsl_pic$ID == "bsc_libeth",],aes(x = dominant, y = Segra_bsl, color = as.factor(lib_eth), shape = orientation_bsl)) + 
  geom_point() + geom_line() +
  scale_shape_manual(name = "Orientation",values = c("Liberal" = "circle","Conservative" = "square")) +
scale_color_manual(values = brewer.pal(11, "Spectral"))+
  facet_grid(orientation_bsl~outcome_bsl, labeller = labeller(outcome_bsl = outcome.labs)) +
  ylab("Outcome") +
  xlab("ß dominant") +
  theme_bw() +
  guides(color = guide_legend(title = "w ethnic\nliberal", order = 1), shape = FALSE)
 ggsave("img_analysis/libeth.jpg",width = 7, height = 4)
 
```

```{r conval, include = TRUE}
 outcome.labs <- c("Ethnic exposure", "Density", "Value exposure")
names(outcome.labs) <- c("Ethnic", "Density", "Value")


ggplot(df_bsl_pic[df_bsl_pic$ID == "bsc_conval",],aes(x = dominant, y = Segra_bsl, color = as.factor(con_val), shape = orientation_bsl)) + 
  geom_point() + geom_line() +
  scale_shape_manual(name = "Orientation",values = c("Liberal" = "circle","Conservative" = "square")) +
scale_color_manual(values = brewer.pal(11, "Spectral"))+
  facet_grid(orientation_bsl~outcome_bsl, labeller = labeller(outcome_bsl = outcome.labs)) +
  ylab("Outcome") +
  xlab("ß dominant") +
  theme_bw() +
  guides(color = guide_legend(title = "w value\nconservative", order = 1), shape = FALSE)
  ggsave("img_analysis/conval.jpg",width = 7, height = 4)
```


```{r asym_native, include = TRUE}

wmaj.labs <- c("w ethnic\nliberal native\n0", "w ethnic\nliberal native\n0.5", "w ethnic\nliberal native\n1")
names(wmaj.labs) <- c("0", "0.5", "1")

 df_asm_bsl %>% filter(ID == "valuesize") %>%   filter(liberal_maj == 80) %>% 
  filter(type %in% c("Conservative Native","Liberal Native")) %>% filter(outcome %in% c("Ethnic","Value")) %>%
ggplot(aes(x = dominant, y = Segra_asm,shape = outcome, color = as.factor(eth_lib_min)
           )) +
  geom_point(size =2) + geom_line() +
 
 scale_color_manual(values = c("0" = "orange","0.5" = "red","1" = "brown"))+
    scale_shape_manual(values = c("Ethnic" = "diamond","Value" = "asterisk")) +
   xlab("ß dominant") +
   ylab("Exposure") +
  facet_grid(eth_lib_maj~type, labeller = labeller(eth_lib_maj = wmaj.labs)) +
   scale_y_continuous(breaks = c(0.4,0.5,0.6,0.8,1)) +
   geom_hline(yintercept = 0.5,linetype = "dashed") +
  theme_bw() +
guides(shape = guide_legend(title = "Exposure",order = 2), color = guide_legend(title = "w ethnic\nliberal migrant",order = 1))
 ggsave("img_analysis/asym_native.jpg",width = 6,height = 5)



```

```{r asym_migrant, include = TRUE}

wmaj.labs <- c("w ethnic\nliberal native\n0", "w ethnic\nliberal native\n0.5", "w ethnic\nliberal native\n1")
names(wmaj.labs) <- c("0", "0.5", "1")

df_asm_bsl %>% filter(ID == "valuesize") %>% filter(liberal_maj == 80) %>% 
  filter(type %in% c("Liberal Migrant","Conservative Migrant")) %>% filter(outcome %in% c("Ethnic","Value")) %>%
ggplot(aes(x = dominant, y = Segra_asm,shape = outcome, color = as.factor(eth_lib_min)
           )) +
  geom_point(size =2) + geom_line() +
 
 scale_color_manual(values = c("0" = "orange","0.5" = "red","1" = "brown"))+
    scale_shape_manual(values = c("Ethnic" = "diamond","Value" = "asterisk","Density" = "plus")) +
   xlab("ß dominant") +
   ylab("Exposure") +
  facet_grid(eth_lib_maj~factor(type, levels = c("Conservative Migrant","Liberal Migrant")), labeller = labeller(eth_lib_maj = wmaj.labs)) +
    geom_hline(yintercept = 0.5,linetype = "dashed") +
    scale_y_continuous(breaks = c(0.2,0.4,0.5,0.6,0.8,1)) +
  theme_bw() +
guides(shape = guide_legend(title = "Exposure",order = 2), color = guide_legend(title = "w ethnic\nliberal migrant",order = 1))
ggsave("img_analysis/asym_migrant.jpg",width = 6,height = 5)


```



# ANNEX ####


```{r asym_native_density, include = TRUE}

wmaj.labs <- c("w ethnic\nliberal native\n0", "w ethnic\nliberal native\n0.5", "w ethnic\nliberal native\n1")
names(wmaj.labs) <- c("0", "0.5", "1")

 df_asm_bsl %>% filter(ID == "valuesize") %>%   filter(liberal_maj == 80) %>% 
  filter(type %in% c("Conservative Native","Liberal Native")) %>%
ggplot(aes(x = dominant, y = Segra_asm,shape = outcome, color = as.factor(eth_lib_min)
           )) +
  geom_point(size =2) + geom_line() +
 
 scale_color_manual(values = c("0" = "orange","0.5" = "red","1" = "brown"))+
    scale_shape_manual(values = c("Ethnic" = "diamond","Value" = "asterisk","Density" = "plus"), labels = c("Ethnic exposure", "Density", "Value exposure")) +
   xlab("ß dominant") +
   scale_y_continuous(name = "Outcome",breaks = seq(0.4,1,by=0.1)) +
 #  ylab("Outcome") +
  facet_grid(eth_lib_maj~type, labeller = labeller(eth_lib_maj = wmaj.labs)) +
     geom_hline(yintercept = 0.5,linetype = "dashed") +
  theme_bw() +
guides(shape = guide_legend(title = "Outcome",order = 2), color = guide_legend(title = "w ethnic\nliberal migrant",order = 1))
 ggsave("img_analysis/asym_nativedensity.jpg",width = 6,height = 5)



```

```{r asym_native_density50, include = TRUE}

wmaj.labs <- c("w ethnic\nliberal native\n0", "w ethnic\nliberal native\n0.5", "w ethnic\nliberal native\n1")
names(wmaj.labs) <- c("0", "0.5", "1")

 df_asm_bsl %>% filter(ID == "valuesize") %>%   filter(liberal_maj == 50) %>% 
  filter(type %in% c("Conservative Native","Liberal Native")) %>%
ggplot(aes(x = dominant, y = Segra_asm,shape = outcome, color = as.factor(eth_lib_min)
           )) +
  geom_point(size =2) + geom_line() +
 
 scale_color_manual(values = c("0" = "orange","0.5" = "red","1" = "brown"))+
    scale_shape_manual(values = c("Ethnic" = "diamond","Value" = "asterisk","Density" = "plus"),
                       labels = c("Ethnic exposure", "Density", "Value exposure")) +
   xlab("ß dominant") +
   scale_y_continuous(name = "Outcome",breaks = seq(0.4,1,by=0.1)) +
 #  ylab("Outcome") +
  facet_grid(eth_lib_maj~type, labeller = labeller(eth_lib_maj = wmaj.labs)) +
     geom_hline(yintercept = 0.5,linetype = "dashed") +
  theme_bw() +
guides(shape = guide_legend(title = "Outcome",order = 2), color = guide_legend(title = "w ethnic\nliberal migrant",order = 1))
 ggsave("img_analysis/asym_nativedensity50.jpg",width = 6,height = 5)



```

```{r asym_migrant_density, include = TRUE}

wmaj.labs <- c("w ethnic\nliberal native\n0", "w ethnic\nliberal native\n0.5", "w ethnic\nliberal native\n1")
names(wmaj.labs) <- c("0", "0.5", "1")

df_asm_bsl %>% filter(ID == "valuesize") %>% filter(liberal_maj == 80) %>% 
  filter(type %in% c("Conservative Migrant","Liberal Migrant")) %>%
ggplot(aes(x = dominant, y = Segra_asm,shape = outcome, color = as.factor(eth_lib_min)
           )) +
  geom_point(size =2) + geom_line() +
 
 scale_color_manual(values = c("0" = "orange","0.5" = "red","1" = "brown"))+
    scale_shape_manual(values = c("Ethnic" = "diamond","Value" = "asterisk","Density" = "plus"),
    labels = c("Ethnic exposure", "Density", "Value exposure")) +
  scale_y_continuous(name = "Outcome",breaks = seq(0.2,1,by=0.1)) +
    xlab("ß dominant") +
   ylab("Outcome") +
  facet_grid(eth_lib_maj~factor(type, levels = c("Conservative Migrant","Liberal Migrant")), labeller = labeller(eth_lib_maj = wmaj.labs)) +
   geom_hline(yintercept = 0.5,linetype = "dashed") +
  theme_bw() +
guides(shape = guide_legend(title = "Outcome",order = 2), color = guide_legend(title = "w ethnic\nliberal migrant",order = 1))
 ggsave("img_analysis/asym_migrantdensity.jpg",width = 6,height = 5)


```

```{r asym_migrant_density50, include = TRUE}

wmin.labs <- c("w ethnic\nliberal migrant\n0", "w ethnic\nliberal migrant\n0.5", "w ethnic\nliberal migrant\n1")
names(wmin.labs) <- c("0", "0.5", "1")

df_asm_bsl %>% filter(ID == "valuesize") %>% filter(liberal_maj == 50) %>% 
  filter(type %in% c("Conservative Migrant","Liberal Migrant")) %>%
ggplot(aes(x = dominant, y = Segra_asm,shape = outcome, color = as.factor(eth_lib_maj)
           )) +
  geom_point(size =2) + geom_line() +
 
 scale_color_manual(values = c("0" = "orange","0.5" = "red","1" = "brown"))+
    scale_shape_manual(values = c("Ethnic" = "diamond","Value" = "asterisk","Density" = "plus"),
                       labels = c("Ethnic exposure", "Density", "Value exposure")) +
  scale_y_continuous(name = "Outcome",breaks = seq(0.2,1,by=0.1)) +
    xlab("ß dominant") +
   ylab("Outcome") +
  facet_grid(eth_lib_min~factor(type, levels = c("Conservative Migrant","Liberal Migrant")), labeller = labeller(eth_lib_min = wmin.labs)) +
   geom_hline(yintercept = 0.5,linetype = "dashed") +
  theme_bw() +
guides(shape = guide_legend(title = "Outcome",order = 2), color = guide_legend(title = "w ethnic\nliberal native",order = 1))
 ggsave("img_analysis/asym_migrantdensity50.jpg",width = 6,height = 5)


```


```{r asym_value_annex, include = TRUE}

wmaj.labs <- c("w ethnic\nliberal native\n0", "w ethnic\nliberal native\n0.5", "w ethnic\nliberal native\n1")
names(wmaj.labs) <- c("0", "0.5", "1")
wmin.labs <- c("w ethnic\nliberal migrant\n0", "w ethnic\nliberal migrant\n0.5", "w ethnic\nliberal migrant\n1")
names(wmin.labs) <- c("0", "0.5", "1")

#sbj <- "Conservative Migrant"
for (sbj in c("Liberal Migrant","Conservative Migrant","Liberal Native","Conservative Native")) {
  

et <- df_asm_bsl %>% filter(ID == "valuesize") %>% 
  filter(type == sbj) %>% filter(outcome == "Ethnic") %>%
ggplot(aes(x = dominant, y = Segra_asm, color = as.factor(liberal_maj)
           )) +
  geom_point(size =2,shape="circle") + geom_line() +
 
 scale_color_manual("% Liberal Native/\n% Liberal Migrant", values = c("50" = "coral2", "60" = "olivedrab", "70" = "cyan", "80" = "violet"), 
                     labels = c("50" = "50/50", "60" = "60/40", "70" = "70/30", "80" = "80/20")
                     
                     ) +
 #   scale_shape_manual(values = c("Ethnic" = "diamond","Value" = "asterisk","Density" = "plus")) +
 # scale_y_continuous(name = "Outcome",breaks = seq(0.2,1,by=0.1)) +
   ylab("Ethnic Exposture") +
  xlab("ß dominant") +
  facet_grid(eth_lib_maj~eth_lib_min , labeller = labeller(eth_lib_maj = wmaj.labs, eth_lib_min = wmin.labs)) + 
   geom_hline(yintercept = 0.5,linetype = "dashed") +
  theme_bw() + 
  theme(legend.position = "bottom") 


vl <- df_asm_bsl %>% filter(ID == "valuesize") %>% 
  filter(type == sbj)  %>% filter(outcome == "Value") %>%
ggplot(aes(x = dominant, y = Segra_asm, color = as.factor(liberal_maj)
           )) +
  geom_point(size =2,shape="circle") + geom_line() +
 
 scale_color_manual("% Liberal Native\n% Liberal Migrant", values = c("50" = "coral2", "60" = "olivedrab", "70" = "cyan", "80" = "violet"), 
                     labels = c("50" = "50/50", "60" = "60/40", "70" = "70/30", "80" = "80/20")
                     
                     ) +
 #   scale_shape_manual(values = c("Ethnic" = "diamond","Value" = "asterisk","Density" = "plus")) +
 # scale_y_continuous(name = "Outcome",breaks = seq(0.2,1,by=0.1)) +
   ylab("Value Exposture") +
  xlab("ß dominant") +
  facet_grid(eth_lib_maj~eth_lib_min , labeller = labeller(eth_lib_maj = wmaj.labs, eth_lib_min = wmin.labs)) + 
   geom_hline(yintercept = 0.5,linetype = "dashed") +
  theme_bw() + 
  theme(legend.position = "bottom") 



pic <- annotate_figure(ggpubr::ggarrange(et,vl, common.legend = T, legend = "right",nrow = 2), 
                top = text_grob(sbj, size = 12))
ggsave(pic, file = paste0("img_analysis/",sbj,"_vlsz.jpg"), width = 6, height = 8)
}
# ggpubr::ggarrange(et,vl, common.legend = T, legend = "bottom")


```

```{r asym_ethnic_annex, include = TRUE}

wmaj.labs <- c("w ethnic\nliberal native\n0", "w ethnic\nliberal native\n0.5", "w ethnic\nliberal native\n1")
names(wmaj.labs) <- c("0", "0.5", "1")
wmin.labs <- c("w ethnic\nliberal migrant\n0", "w ethnic\nliberal migrant\n0.5", "w ethnic\nliberal migrant\n1")
names(wmin.labs) <- c("0", "0.5", "1")

for (sbj in c("Liberal Migrant","Conservative Migrant","Liberal Native","Conservative Native")){

et <- df_asm_pic %>% filter(ID == "ethnicsize") %>% 
  filter(type == sbj) %>% filter(outcome == "Ethnic") %>%
ggplot(aes(x = dominant, y = Segra_asm, color = as.factor(majority)
           )) +
  geom_point(size =2,shape="circle") + geom_line() +
 
 scale_color_manual("% Ethnic Native / % Ethnic Migrant", values = c("50" = "coral2", "60" = "olivedrab", "70" = "cyan", "80" = "violet"), 
                     labels = c("50" = "50/50", "60" = "60/40", "70" = "70/30", "80" = "80/20")
                     
                     ) +
 #   scale_shape_manual(values = c("Ethnic" = "diamond","Value" = "asterisk","Density" = "plus")) +
 # scale_y_continuous(name = "Outcome",breaks = seq(0.2,1,by=0.1)) +
   ylab("Ethnic Exposture") +
  xlab("ß dominant") +
  facet_grid(eth_lib_maj~eth_lib_min , labeller = labeller(eth_lib_maj = wmaj.labs, eth_lib_min = wmin.labs)) + 
   geom_hline(yintercept = 1,linetype = "dashed") +
  theme_bw() + 
  theme(legend.position = "bottom") 


vl <- df_asm_pic %>% filter(ID == "ethnicsize") %>% 
  filter(type == sbj)  %>% filter(outcome == "Value") %>%
ggplot(aes(x = dominant, y = Segra_asm, color = as.factor(majority)
           )) +
  geom_point(size =2,shape="circle") + geom_line() +
 
 scale_color_manual("% Ethnic Native / % Ethnic Migrant", values = c("50" = "coral2", "60" = "olivedrab", "70" = "cyan", "80" = "violet"), 
                     labels = c("50" = "50/50", "60" = "60/40", "70" = "70/30", "80" = "80/20")
                     
                     ) +
 #   scale_shape_manual(values = c("Ethnic" = "diamond","Value" = "asterisk","Density" = "plus")) +
 # scale_y_continuous(name = "Outcome",breaks = seq(0.2,1,by=0.1)) +
   ylab("Value Exposture") +
  xlab("ß dominant") +
  facet_grid(eth_lib_maj~eth_lib_min , labeller = labeller(eth_lib_maj = wmaj.labs, eth_lib_min = wmin.labs)) + 
   geom_hline(yintercept = 1,linetype = "dashed") +
  theme_bw() + 
  theme(legend.position = "bottom") 



picet <- annotate_figure(ggpubr::ggarrange(et,vl, common.legend = T, legend = "bottom",nrow = 2), 
                top = text_grob(sbj, size = 12))
ggsave(picet, file = paste("img_analysis/",sbj,"_etsz.jpg"), width = 6, height = 9)
# ggpubr::ggarrange(et,vl, common.legend = T, legend = "bottom")
}

```




